import React, { useState, useEffect } from 'react';
import { getSessions } from '../../lib/storage';
import './Dashboard.css';

const SparklesIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="badge-icon"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/></svg>
);

const CheckIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#10b981" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/></svg>
);

const AlertIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
);

const ArrowRightIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
);

const Dashboard = () => {
  const [sessions, setSessions] = useState([]);
  const [selectedSession, setSelectedSession] = useState(null);

  useEffect(() => {
    const list = getSessions();
    setSessions(list);
    if (list.length > 0) {
      setSelectedSession(list[0]);
    }
  }, []);

  const completedSessions = sessions.filter(s => s.status === 'completed');
  const inProgressSessions = sessions.filter(s => s.status !== 'completed');

  return (
    <div className="dashboard-container">
      <div className="badge program-badge">
        <SparklesIcon /> Candidate dashboard
      </div>
      
      <h1 className="program-title">Interview sessions</h1>
      <p className="program-subtitle">
        Every interview is assigned a unique session ID. Review candidate attempts,<br/>
        questions asked, and the structured feedback generated by the AI interviewer.
      </p>
      
      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-label">TOTAL SESSIONS</div>
          <div className="stat-value">{sessions.length}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">COMPLETED</div>
          <div className="stat-value">{completedSessions.length}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">IN PROGRESS</div>
          <div className="stat-value">{inProgressSessions.length}</div>
        </div>
      </div>
      
      <div className="dashboard-layout">
        <div className="sessions-list">
          {sessions.length === 0 ? (
            <div style={{ color: 'var(--text-muted)' }}>No sessions found. Start a new interview to see it here.</div>
          ) : (
            sessions.map(session => {
              const candName = session.candidate?.member?.name || session.candidate?.name || 'Candidate';
              const candRole = session.candidate?.member?.jobRole || session.candidate?.role || 'AI Engineer';
              const candExp = session.candidate?.member?.yearsExperience 
                ? `${session.candidate.member.yearsExperience} yrs`
                : session.candidate?.experience || '';

              return (
                <div 
                  key={session.id} 
                  className={`session-card ${selectedSession?.id === session.id ? 'active' : ''}`} 
                  onClick={() => setSelectedSession(session)} 
                  style={{ cursor: 'pointer', border: selectedSession?.id === session.id ? '1px solid var(--text)' : '1px solid var(--border)' }}
                >
                  <div className="session-card-header">
                    <span className="session-tag"># {session.id}</span>
                    {session.status === 'completed' ? (
                      <div className="score-badge" style={{ background: '#dcfce7', color: '#15803d' }}>
                        ✓ Completed
                      </div>
                    ) : (
                      <div className="score-badge" style={{ background: '#fef3c7', color: '#b45309' }}>
                        In Progress
                      </div>
                    )}
                  </div>
                  <h3 className="session-name">{candName}</h3>
                  <p className="session-role">{candRole} {candExp ? `· ${candExp}` : ''}</p>
                </div>
              );
            })
          )}
        </div>
        
        <div className="feedback-preview-pane" style={selectedSession ? { display: 'block', border: 'none', background: 'transparent' } : {}}>
          {!selectedSession ? (
            "Select a session to view its feedback."
          ) : selectedSession.status !== 'completed' ? (
            <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: '12px', padding: '32px', color: 'var(--text-muted)' }}>
              <h3 style={{ marginBottom: '8px', color: 'var(--text)' }}>Session in Progress</h3>
              <p>This interview is currently in progress. Complete all 8 questions to generate the final structured evaluation.</p>
            </div>
          ) : (
            <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: '12px', padding: '32px' }}>
              <h2 style={{ fontSize: '20px', fontWeight: 700, marginBottom: '24px' }}>
                {selectedSession.candidate?.member?.name || selectedSession.candidate?.name || 'Candidate'}'s Evaluation
              </h2>
              
              <div style={{ marginBottom: '24px' }}>
                <h3 style={{ fontSize: '12px', fontWeight: 700, letterSpacing: '1px', color: 'var(--primary)', marginBottom: '8px' }}>SUMMARY</h3>
                <p style={{ fontSize: '14px', lineHeight: 1.6, color: 'var(--text)' }}>{selectedSession.feedback?.summary}</p>
              </div>

              <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', marginBottom: '24px' }}>
                <div style={{ flex: 1, minWidth: '250px' }}>
                  <h3 style={{ fontSize: '12px', fontWeight: 700, letterSpacing: '1px', color: '#10b981', marginBottom: '12px' }}>STRENGTHS</h3>
                  <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '8px', padding: 0 }}>
                    {selectedSession.feedback?.strengths?.map((s, i) => (
                      <li key={i} style={{ display: 'flex', gap: '8px', fontSize: '14px' }}><CheckIcon /> <span style={{ flex: 1 }}>{s}</span></li>
                    ))}
                  </ul>
                </div>
                <div style={{ flex: 1, minWidth: '250px' }}>
                  <h3 style={{ fontSize: '12px', fontWeight: 700, letterSpacing: '1px', color: '#ef4444', marginBottom: '12px' }}>GAPS</h3>
                  <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '8px', padding: 0 }}>
                    {selectedSession.feedback?.gaps?.map((g, i) => (
                      <li key={i} style={{ display: 'flex', gap: '8px', fontSize: '14px' }}><AlertIcon /> <span style={{ flex: 1 }}>{g}</span></li>
                    ))}
                  </ul>
                </div>
              </div>

              {Array.isArray(selectedSession.feedback?.next) && selectedSession.feedback.next.length > 0 && (
                <div>
                  <h3 style={{ fontSize: '12px', fontWeight: 700, letterSpacing: '1px', color: 'var(--primary)', marginBottom: '12px' }}>RECOMMENDED NEXT STEPS</h3>
                  <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '8px', padding: 0 }}>
                    {selectedSession.feedback.next.map((n, i) => (
                      <li key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', color: 'var(--text)' }}>
                        <ArrowRightIcon /> <span>{n}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
